//
// Created by nyam on 06.04.17.
//

#ifndef MYGAME_DEFINITIONS_H
#define MYGAME_DEFINITIONS_H

#define PLAYER_BITMASK 0x000001
#define GROUND_BITMASK  0x000002
#define OBSTACLE_COLLISION_BITMASK  0x000000

#define SPEED_OF_THE_PLAYER 4
#define SPEED_OF_THE_PLAYER_IN_THE_AIR 2

#endif //MYGAME_DEFINITIONS_H
